openapi: 3.0.3
info:
  title: Coding-Service-API
  description: Coding-Service-API
  version: 0.2.0-alpha
paths:
  /info:
    get:
      summary: return conding service identification
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceInfo"
        "500":
          description: server error
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/Error"

  /tasks:
    put:
      summary: add a task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskUpdate"
            example: { type: train }
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "500":
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    get:
      summary: get list of all tasks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "500":
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tasks/{task_id}:
    get:
      summary: get specific task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        404:
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: update instructions or other fields
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskUpdate"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        404:
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        422:
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: OK, deleted
        404:
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tasks/{task_id}/{action}:
    post:
      summary: perform action on task
      description: perform an action on task |
        common actions are `abort` and `commit`
      parameters:
        - in: path
          name: action
          description: action name, usually `abort` or `commit`
          required: true
          schema:
            $ref: "#/components/schemas/TaskAction"
          example: commit
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        404:
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        422:
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tasks/{task_id}/data:
    put:
      summary: add a chunk of data for a specific task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataSet"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataChunk"
        404:
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        422:
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /tasks/{task_id}/data/{chunk_id}:
    get:
      summary: retrieve a chunk of data from a specific task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
        - in: path
          name: chunk_id
          required: true
          schema:
            $ref: "#/components/schemas/ChunkId"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataSet"
        404:
          description: Task or chunk not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: delete a chunk of data from a specific task
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            $ref: "#/components/schemas/TaskId"
        - in: path
          name: chunk_id
          required: true
          schema:
            $ref: "#/components/schemas/ChunkId"
      responses:
        200:
          description: OK, deleted
        403:
          description: deletion not allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Task or chunk not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /coders:
    get:
      summary: list as available coders
      description: Returns a list of available coders. What a coder is depends to the implementation of the api. In most
        cases it will be a pretrained model. It also could be a specific set of instructions.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoderList"
        403:
          description: deletion not allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /coders/{coder_id}:
    delete:
      summary: delete coder
      parameters:
        - in: path
          name: coder_id
          required: true
          schema:
            $ref: "#/components/schemas/CoderId"
      responses:
        200:
          description: OK, deleted
        403:
          description: deletion not allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Coder not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    ServiceInfo:
      type: object
      properties:
        id:
          type: string
          example: 'ExampleCodingService1'
        type:
          type: string
          example: 'example-coding-service'
        version:
          type: string
          example: '1.0.2'
          pattern: ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$
        apiVersion:
          type: string
          example: '0.0.1'
          pattern: ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$
        instructionsText:
          type: string
        instructionsSchema:
          type: object
          properties:
            "$id":
              type: string
            "$schema":
              type: string
              enum:
                - http://json-schema.org/draft/2020-12/schema#
                - http://json-schema.org/draft/2019-09/schema#
                - http://json-schema.org/draft-07/schema#
          required:
            - $id
            - $schema
        mode:
          $ref: "#/components/schemas/ServiceMode"
      required:
        - id
        - type
        - version
        - apiVersion
        - instructionsSchema

    ServiceMode:
      type: string
      enum:
        - 'train+code'
        - 'direct'
      example: 'train+code'
      default: 'train+code'
      description: |
        Mode of operation of this service. 
        * "train+code" - You have to prepare a coder in a first step (training a model for example) with
          given instructions and training data. In a second step you select this coder and and code a list of data.
        * "direct" - There is only one type of task, "code" and it does the coding directly from instructions. 

    TaskId:
      type: string
      example: 'task#1234569'

    TaskType:
      type: string
      enum:
        - 'train'
        - 'code'
        - 'unknown'
      example: 'train'

    TaskAction:
      type: string
      enum:
        - 'commit'
        - 'abort'
      example: 'commit'

    Task:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/TaskId"
        label:
          type: string
        type:
          $ref: "#/components/schemas/TaskType"
        coder:
          $ref: "#/components/schemas/CoderId"
        instructions:
          $ref: "#/components/schemas/TaskInstructions"
        events:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                enum: [ 'create', 'commit', 'start', 'progress', 'warning', 'fail', 'finish', 'abort' ]
              message:
                type: string
              timestamp:
                type: integer
                description: milliseconds since UTC epoch
        data:
          type: array
          items:
            $ref: "#/components/schemas/DataChunk"
      required:
        - id
        - label
        - type
        - events
        - data
      example:
        id: "123456"
        type: "train"
        label: "example task"
        events:
          - status: "create"
            message: "task created"
            timestamp: 1749644764948627
        data:
          - id: "chunk1"
            type: "input"

    TaskUpdate:
      type: object
      properties:
        label:
          type: string
        type:
          $ref: "#/components/schemas/TaskType"
        instructions:
          $ref: "#/components/schemas/TaskInstructions"
        coder:
          $ref: "#/components/schemas/CoderId"

    ChunkId:
      type: string
      example: "chunk#13346"

    ChunkType:
      type: string
      enum:
        - "input"
        - "output"
      example: "input"

    DataChunk:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/ChunkId"
        type:
          $ref: "#/components/schemas/ChunkType"
      required:
        - id
        - type

    DataSet:
      type: array
      items:
        $ref: "#/components/schemas/Response"
      example:
        [
          { setId: 'user1',  id: 'a', value: 'some answer', status: 'VALUE_CHANGED' },
          { setId: 'user1',  id: 'b', value: 'some other answer', status: 'VALUE_CHANGED' },
          { setId: 'user2',  id: 'a', value: 'some answer', status: 'VALUE_CHANGED' },
          { setId: 'user2',  id: 'b', value: 'trash answer', status: 'VALUE_CHANGED' },
        ]

    Response: # TODO use reference to spec repo here
      title: Response
      description: Data structure produced by verona players
      type: object
      properties:
        setId:
          type: string
          description: Identifier of the set. Typically a user-id.
        id:
          type: string
          pattern: ^[0-9a-zA-Z_-]+$
          description: Identifier for the data source (variable)
        status:
          type: string
          enum:
           - UNSET
           - NOT_REACHED
           - DISPLAYED
           - VALUE_CHANGED
           - DERIVE_ERROR
           - CODING_COMPLETE
           - NO_CODING
           - INVALID
           - CODING_INCOMPLETE
           - CODING_ERROR
           - PARTLY_DISPLAYED
           - DERIVE_PENDING
           - INTENDED_INCOMPLETE
           - CODE_SELECTION_PENDING
          description: Status as stage in the workflow of creating and coding a variable's value
        value:
          anyOf:
            - type: array
              items:
                type: string
            - type: array
              items:
                type: number
            - type: array
              items:
                type: boolean
            - type: number
            - type: string
            - type: boolean
        subform:
          type: string
          description: If variables i. e. data source ids are not unique in the unit, 'subform' can specify the sub object related to the specific variable.
        code:
          type: integer
          description: Code representing the category of the value after coding process.
        score:
          type: integer
          description: This value represents the result evaluation of the code after coding process.
        codes:
          type: array
          items:
            $ref: "#/components/schemas/Code"
          description: List of possible codes if status is CODE_SELECTION_PENDING.
      required:
        - setId
        - id
        - status
        - value

    Code:
      type: object
      properties:
        id:
          type: integer
          description: Code representing the category option.
        parameter:
          type: string
          description: Specifies the code to support the code selection.
      required:
        - id

    CoderId:
      type: string
      example: "coder#123"

    Coder:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/CoderId"
        label:
          type: string
      required:
        - id
        - label

    CoderList:
      type: array
      items:
        $ref: "#/components/schemas/Coder"

    TaskInstructions:
      type: object
      description: This should be overwritten in a concrete implementation of the API

    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
