### get info
GET {{server}}/info


### list tasks
GET {{server}}/tasks

### add Task
PUT {{server}}/tasks
Content-Type: application/json

{
  "type": "train",
  "instructions": {}
}

> {% client.global.set("task_id", response.body.id); %}

### commit task
PATCH {{server}}/tasks/{{task_id}}
Content-Type: application/json

{
  "action": "commit"
}

### get task again and store output chunk id
GET {{server}}/tasks/{{task_id}}

> {% client.global.set("chunk_id", response.body.data.find(d => d.type === 'output').id) %}

### get chunk
GET {{server}}/tasks/{{task_id}}/data/{{chunk_id}}


### abort task
PATCH {{server}}/tasks/{{task_id}}
Content-Type: application/json

{
  "action": "abort"
}

###
DELETE {{server}}/tasks/{{task_id}}

### add chunk
PUT {{server}}/tasks/{{task_id}}/data
Content-Type: application/json

[
  { "id": "a", "value": "A", "status": "VALUE_CHANGED" },
  { "id": "b", "value": "B", "status": "VALUE_CHANGED" },
  { "id": "c", "value": "C", "status": "VALUE_CHANGED" },
  { "id": "d", "value": "D", "status": "VALUE_CHANGED" }
]






###
DELETE {{server}}/tasks/{{task_id}}/data/{{chunk_id}}
