### get info
GET {{server}}/info


### list tasks
GET {{server}}/tasks

### add Task
PUT {{server}}/tasks
Content-Type: application/json

{
  "type": "train",
  "instructions": {}
}

> {% client.global.set("task_id", response.body.id); %}

### get task
GET {{server}}/tasks/{{task_id}}



### commit task
PATCH {{server}}/tasks/{{task_id}}
Content-Type: application/json

{
  "action": "commit"
}

### abort task
PATCH {{server}}/tasks/{{task_id}}
Content-Type: application/json

{
  "action": "abort"
}

###
DELETE {{server}}/tasks/{{task_id}}

### add chunk
PUT {{server}}/tasks/{{task_id}}/data
Content-Type: application/json

[
  { "id": "a", "value": "A", "status": "VALUE_CHANGED" },
  { "id": "b", "value": "B", "status": "VALUE_CHANGED" },
  { "id": "c", "value": "C", "status": "VALUE_CHANGED" },
  { "id": "d", "value": "D", "status": "VALUE_CHANGED" }
]


### get chunk
@chunk_id = test
GET {{server}}/tasks/{{task_id}}/data/{{chunk_id}}



###
DELETE {{server}}/tasks/{{task_id}}/data/{{chunk_id}}
