on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Generate Html an publish

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Prepare repo
        run: |
          git fetch origin
          git config --global user.email "a@b.c"
          git config --global user.name "GitLab"
          git checkout gh-pages
          git reset --hard main
          mkdir docs
      - name: Run html generation
        run: |
          npm ci
          npm run generate_docs
      - name: Push changes
        run: |
          git add docs
          git commit -m "update gh-pages"
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
